### ISSUE TITLE
Support for exporting metrics to Grafana Cloud

### ISSUE THREAD

**Issue by ishanjainn** [dokulabs/doku#4]
I really like this project, Ive been working on similar project for [grafana-openai-monitoring](https://github.com/grafana/grafana-openai-monitoring). 

Right now I see the export to Grafana Cloud only exports logs, But I suggest you can us ethe influx line protocol to send metrics over HTTP to Grafana Cloud.

I can actually add support for this

**Comment by patcher99** [comment]
Yup Makes sense, Looking forward to the Pull Request
